AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ClubHub API - FastAPI Backend on AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        APP_NAME: ClubHub API
        APP_VERSION: 1.0.0
        DEBUG: false
        USE_LOCAL_STORAGE: true
        # Lambda has /tmp directory for temporary storage (512MB max)
        LOCAL_STORAGE_PATH: /tmp/uploads
        DATABASE_URL: sqlite:////tmp/clubhub.db
        JWT_ALGORITHM: HS256
        JWT_EXPIRE_MINUTES: 1440

Parameters:
  JWTSecretKey:
    Type: String
    NoEcho: true
    Description: Secret key for JWT token generation
    Default: change-this-to-a-secure-random-string

  FrontendURL:
    Type: String
    Description: URL of your frontend (for CORS)
    Default: https://main.d1234567890.amplifyapp.com

  UseS3Storage:
    Type: String
    Description: Set to 'true' to use S3, 'false' to use local Lambda storage
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  S3BucketName:
    Type: String
    Description: S3 bucket name for photo storage (optional)
    Default: clubhub-photos

Resources:
  # Lambda Function
  ClubHubAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clubhub-api
      CodeUri: .
      Handler: lambda_handler.handler
      Description: ClubHub FastAPI Backend
      Environment:
        Variables:
          JWT_SECRET_KEY: !Ref JWTSecretKey
          CORS_ORIGINS: !Ref FrontendURL
          FRONTEND_URL: !Ref FrontendURL
          LOCAL_STORAGE_URL_PREFIX: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/uploads
          S3_BUCKET_NAME: !Ref S3BucketName
          AWS_REGION: !Ref AWS::Region
      Events:
        # HTTP API (API Gateway v2) - cheaper and simpler than REST API
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref ServerlessHttpApi
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName

  # HTTP API (API Gateway v2)
  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - !Ref FrontendURL
          - http://localhost:5173
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS
        AllowCredentials: true

  # S3 Bucket for Photos (Optional)
  PhotosBucket:
    Type: AWS::S3::Bucket
    Condition: CreateS3Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - !Ref FrontendURL
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - "*"
            MaxAge: 3600

  # S3 Bucket Policy for Public Read
  PhotosBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateS3Bucket
    Properties:
      Bucket: !Ref PhotosBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub ${PhotosBucket.Arn}/*

Conditions:
  CreateS3Bucket: !Equals [!Ref UseS3Storage, 'true']

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
    Export:
      Name: ClubHubApiEndpoint

  ApiId:
    Description: API Gateway ID
    Value: !Ref ServerlessHttpApi

  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ClubHubAPI.Arn

  PhotosBucketName:
    Description: S3 Bucket for Photos
    Value: !Ref S3BucketName
    Condition: CreateS3Bucket
